---
output: html_document
editor_options: 
  chunk_output_type: console
---
# (PART) Part Two {-}

# `bmbstats`: Bootstrap Magnitude-based Statistics package

```{r echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# Run common script
source("_common.R")
```

In the first part of this book we have covered descriptive, predictive, and causal inference tasks, followed by the basics of statistical inference using frequentist, Bayesian, and bootstrap methods and concluded with the measurement error explanation. In this part of the book, we will turn to `bmbstats`, which is short of *Bootstrap Magnitude-based Statistics*, package to perform analysis of the most common sports science problems and utilize bootstrap as the inference method of choice.

Since I strongly believe that the best way to understand statistical analysis is through simulations and smart visualizations, in this part of the book I will show the R code that you can use to reproduce the analysis, but more importantly, to understand the underlying DGP we are trying to explain (or estimate) with the analysis. 

## Installation

You can install the development version from [GitHub](https://github.com/mladenjovanovic/bmbstats) with:

``` r
# install.packages("devtools")
devtools::install_github("mladenjovanovic/bmbstats")

require(bmbstats)
```




